/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { DBContext } from "./../context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * UTC Date-time
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "NDDateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * UTC Date-time
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "NDDateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  ContentStatus: "draft" | "live" | "quarantined"
  ReporterType: "experiencer" | "observer" | "researcher"
  UserRoles: "admin" | "dataentry" | "moderator" | "researcher"
  VideoSource: "other" | "vimeo" | "youtube"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  NDDateTime: any
}

export interface NexusGenObjects {
  Mutation: {};
  NDBook: { // root type
    addedBy: number; // Int!
    id?: string | null; // ID
    lastUpdated?: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    publishDate?: string | null; // String
    publisher?: string | null; // String
    reporterId: number; // Int!
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    title: string; // String!
  }
  NDBookTag: { // root type
    ContentTag?: NexusGenRootTypes['NDContentTag'] | null; // NDContentTag
    addedBy: number; // Int!
    bookId: number; // Int!
    id?: string | null; // ID
    lastUpdated?: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    reporterId: number; // Int!
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    tagId: number; // Int!
  }
  NDContentTag: { // root type
    description: string; // String!
    example?: string | null; // String
    id?: string | null; // ID
    name: string; // String!
  }
  NDReporter: { // root type
    addedBy: number; // Int!
    id?: string | null; // ID
    lastUpdated?: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    name: string; // String!
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    type: NexusGenEnums['ReporterType']; // ReporterType!
  }
  NDVideo: { // root type
    addedBy: number; // Int!
    id?: string | null; // ID
    lastUpdated?: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    reporterId: number; // Int!
    source?: string | null; // String
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    url: string; // String!
  }
  NDVideoTag: { // root type
    ContentTag?: NexusGenRootTypes['NDContentTag'] | null; // NDContentTag
    addedBy: number; // Int!
    id?: string | null; // ID
    lastUpdated?: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    reporterId: number; // Int!
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    tagId: number; // Int!
    videoId: number; // Int!
  }
  NDWebsite: { // root type
    addedBy: number; // Int!
    id?: string | null; // ID
    lastUpdated?: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    reporterId: number; // Int!
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    url: string; // String!
  }
  NDWebsiteTag: { // root type
    ContentTag?: NexusGenRootTypes['NDContentTag'] | null; // NDContentTag
    addedBy: number; // Int!
    id?: string | null; // ID
    lastUpdated?: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    reporterId: number; // Int!
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    tagId: number; // Int!
    websiteId: number; // Int!
  }
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    createReporter: NexusGenRootTypes['NDReporter'] | null; // NDReporter
  }
  NDBook: { // field return type
    addedBy: number; // Int!
    id: string | null; // ID
    lastUpdated: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    publishDate: string | null; // String
    publisher: string | null; // String
    reporterId: number; // Int!
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    title: string; // String!
  }
  NDBookTag: { // field return type
    ContentTag: NexusGenRootTypes['NDContentTag'] | null; // NDContentTag
    addedBy: number; // Int!
    bookId: number; // Int!
    id: string | null; // ID
    lastUpdated: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    reporterId: number; // Int!
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    tagId: number; // Int!
  }
  NDContentTag: { // field return type
    description: string; // String!
    example: string | null; // String
    id: string | null; // ID
    name: string; // String!
  }
  NDReporter: { // field return type
    addedBy: number; // Int!
    id: string | null; // ID
    lastUpdated: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    name: string; // String!
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    type: NexusGenEnums['ReporterType']; // ReporterType!
  }
  NDVideo: { // field return type
    addedBy: number; // Int!
    id: string | null; // ID
    lastUpdated: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    reporterId: number; // Int!
    source: string | null; // String
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    url: string; // String!
  }
  NDVideoTag: { // field return type
    ContentTag: NexusGenRootTypes['NDContentTag'] | null; // NDContentTag
    addedBy: number; // Int!
    id: string | null; // ID
    lastUpdated: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    reporterId: number; // Int!
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    tagId: number; // Int!
    videoId: number; // Int!
  }
  NDWebsite: { // field return type
    addedBy: number; // Int!
    id: string | null; // ID
    lastUpdated: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    reporterId: number; // Int!
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    url: string; // String!
  }
  NDWebsiteTag: { // field return type
    ContentTag: NexusGenRootTypes['NDContentTag'] | null; // NDContentTag
    addedBy: number; // Int!
    id: string | null; // ID
    lastUpdated: NexusGenScalars['NDDateTime'] | null; // NDDateTime
    reporterId: number; // Int!
    status: NexusGenEnums['ContentStatus']; // ContentStatus!
    tagId: number; // Int!
    websiteId: number; // Int!
  }
  Query: { // field return type
    ok: boolean; // Boolean!
  }
}

export interface NexusGenFieldTypeNames {
  Mutation: { // field return type name
    createReporter: 'NDReporter'
  }
  NDBook: { // field return type name
    addedBy: 'Int'
    id: 'ID'
    lastUpdated: 'NDDateTime'
    publishDate: 'String'
    publisher: 'String'
    reporterId: 'Int'
    status: 'ContentStatus'
    title: 'String'
  }
  NDBookTag: { // field return type name
    ContentTag: 'NDContentTag'
    addedBy: 'Int'
    bookId: 'Int'
    id: 'ID'
    lastUpdated: 'NDDateTime'
    reporterId: 'Int'
    status: 'ContentStatus'
    tagId: 'Int'
  }
  NDContentTag: { // field return type name
    description: 'String'
    example: 'String'
    id: 'ID'
    name: 'String'
  }
  NDReporter: { // field return type name
    addedBy: 'Int'
    id: 'ID'
    lastUpdated: 'NDDateTime'
    name: 'String'
    status: 'ContentStatus'
    type: 'ReporterType'
  }
  NDVideo: { // field return type name
    addedBy: 'Int'
    id: 'ID'
    lastUpdated: 'NDDateTime'
    reporterId: 'Int'
    source: 'String'
    status: 'ContentStatus'
    url: 'String'
  }
  NDVideoTag: { // field return type name
    ContentTag: 'NDContentTag'
    addedBy: 'Int'
    id: 'ID'
    lastUpdated: 'NDDateTime'
    reporterId: 'Int'
    status: 'ContentStatus'
    tagId: 'Int'
    videoId: 'Int'
  }
  NDWebsite: { // field return type name
    addedBy: 'Int'
    id: 'ID'
    lastUpdated: 'NDDateTime'
    reporterId: 'Int'
    status: 'ContentStatus'
    url: 'String'
  }
  NDWebsiteTag: { // field return type name
    ContentTag: 'NDContentTag'
    addedBy: 'Int'
    id: 'ID'
    lastUpdated: 'NDDateTime'
    reporterId: 'Int'
    status: 'ContentStatus'
    tagId: 'Int'
    websiteId: 'Int'
  }
  Query: { // field return type name
    ok: 'Boolean'
  }
}

export interface NexusGenArgTypes {
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: DBContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}